### ISSUE TITLE
The type or namespace name 'RenderImGuiFeature' could not be found 

### ISSUE THREAD

**Issue by Valeour** [realgamessoftware/dear-imgui-unity#2]
Non-URP mode compile error;
`Library/PackageCache/com.realgames.dear-imgui@a47dc01ab8d1b5893db3000d57ee756b2e05ad6a/ImGuiNET.Unity/DearImGui.cs(26,26): error CS0246: The type or namespace name 'RenderImGuiFeature' could not be found (are you missing a using directive or an assembly reference?)`

Changing `RenderCommandBufferFeature` at `RenderImGuiFeature.cs:48` to `RenderImGuiFeature` appears to resolve the error and compiles.

I've just implemented the plugin via package manager, so I haven't yet got a project to test that everything works as normal, and can't confirm that this is the correct fix.

**Comment by goncalo** [comment]
Yes, that is the correct fix. Thank you!
